export const ADD_PRODUCT = 'ADD_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const CLEAR_SHOPPING_CART = 'CLEAR_SHOPPING_CART';
export const OPEN_SHOPPING_CART = 'OPEN_SHOPPING_CART';
